"""userfeed

Revision ID: 6d190fb722e9
Revises: c879097150e0
Create Date: 2024-03-08 13:17:05.676289+11:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d190fb722e9'
down_revision = 'c879097150e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_feed', sa.Column('date_added', sa.DateTime(), nullable=True))
    op.alter_column('user_feed', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_feed', 'feed_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_user_feed_date_added'), 'user_feed', ['date_added'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_feed_date_added'), table_name='user_feed')
    op.alter_column('user_feed', 'feed_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_feed', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('user_feed', 'date_added')
    # ### end Alembic commands ###
