"""your message here

Revision ID: 7c3e354c1224
Revises: b71d0df14d85
Create Date: 2024-03-08 22:41:42.032816+11:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c3e354c1224'
down_revision = 'b71d0df14d85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
