"""your message here

Revision ID: 8ca31bcc2729
Revises: 7c3e354c1224
Create Date: 2024-03-08 22:47:28.245600+11:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca31bcc2729'
down_revision = '7c3e354c1224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
