"""first migration

Revision ID: c879097150e0
Revises: 05b14ff94666
Create Date: 2024-03-06 13:23:48.828480+11:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c879097150e0'
down_revision = '05b14ff94666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
