"""your message here

Revision ID: cfffc67d42e9
Revises: 6d190fb722e9
Create Date: 2024-03-08 21:28:45.575663+11:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cfffc67d42e9'
down_revision = '6d190fb722e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_categories_id', table_name='categories')
    op.drop_table('categories')
    op.add_column('feeds', sa.Column('title', sa.String(), nullable=False))
    op.add_column('feeds', sa.Column('token_n', sa.Integer(), nullable=False))
    op.add_column('feeds', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=512), nullable=True))
    op.create_index(op.f('ix_feeds_title'), 'feeds', ['title'], unique=False)
    op.drop_constraint('feeds_category_id_fkey', 'feeds', type_='foreignkey')
    op.drop_column('feeds', 'text')
    op.drop_column('feeds', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('feeds', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('feeds_category_id_fkey', 'feeds', 'categories', ['category_id'], ['id'])
    op.drop_index(op.f('ix_feeds_title'), table_name='feeds')
    op.drop_column('feeds', 'embedding')
    op.drop_column('feeds', 'token_n')
    op.drop_column('feeds', 'title')
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', postgresql.ENUM('General', 'Sports', 'News', 'Technology', 'Entertainment', 'Lifestyle', 'Business', 'Science', 'Health', 'Education', 'Politics', 'Environment', 'Arts & Culture', name='category_titles'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='categories_pkey')
    )
    op.create_index('ix_categories_id', 'categories', ['id'], unique=False)
    # ### end Alembic commands ###
