version: '3'

services:
  scrape_service:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    volumes:
      - ./scraper:/usr/src/app
    networks:
      - app_network

  generate_embeddings_service:
    build:
      context: ./generate_embeddings
      dockerfile: Dockerfile
    volumes:
      - ./generate_embeddings:/usr/src/app
    networks:
      - app_network

  upsert_db_service:
    build:
      context: ./upsert_db
      dockerfile: Dockerfile
    volumes:
      - ./upsert_db:/usr/src/app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
