# Use an official Python runtime as a parent image
FROM python:latest

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port available to the world outside this container
EXPOSE 8001

# Define environment variable
ENV NAME EmbeddingGenerationService

# Run embedding_generation.py when the container launches
CMD ["python", "embedding_generation.py"]
